# Remember to update the NAME and FRIENDLY_NAME in the substitutions block, and the STATIC_IP in the wifi block!!

substitutions:
  name: lb_0
  friendly_name: lb_0
packages:
  localbytes.plug-pm: github://LocalBytes/esphome-localbytes-plug/localbytes-plug-pm.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.230
    gateway: 192.168.0.1
    subnet: 255.255.255.0
